name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Menambahkan tombol manual "Run workflow" di GitHub Actions

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow dagshub
      
      - name: Download GloVe Embedding
        run: |
          mkdir -p dataset
          wget http://nlp.stanford.edu/data/glove.6B.zip -O dataset/glove.6B.zip
          unzip -j dataset/glove.6B.zip glove.6B.100d.txt -d dataset
      
      - name: Run training script
        run: |
          python mentalhealthcolab.py
      # - name: Deploy, build docker, dsb (opsional)
